title: HOTT WRESTLING
description: The hottest wrestling content. No filters, no censorship.
url: ""
baseurl: ""
permalink: /:year/:month/:day/:title/
timezone: America/Caracas
plugins:
  - jekyll-feed

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "wrestlers"
    values:
      layout: "wrestler"
  - scope:
      path: ""
      type: "studs"
    values:
      layout: "stud"
  - scope:
      path: ""
      type: "bulge"
    values:
      layout: "bulge"
  - scope:
      path: ""
      type: "stories"
    values:
      layout: "story"

collections:
  wrestlers:
    output: true
    permalink: /the-mat/:name/
  badboys:
    output: false
  stories:
    output: true
    permalink: /stories/:slug/
  studs:
    output: true
    permalink: /studs/:name/
  bulge:
    output: true
    permalink: /bulge-sport/:name/
